
server.port=8080

# H2 Database
#spring.datasource.url=jdbc:h2:file:./data/mydb
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:file:./data/mydb;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# JWT
jwt.secret=S2V5X3RoaXNJc1ZlcnlMb25nQW5kUmFuZG9tU2VjcmV0
jwt.expiration=3600000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=912831856789-0urb0shk95jml1gvipo7n5eha2g6snrc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile

logging.level.org.springframework=DEBUG
logging.level.org.apache.catalina=DEBUG
